site_name: "boring mind machine"
site_url: https://pages.charlesreid1.com/boring-mind-machine
repo_name: boring-mind-machine
repo_url: https://github.com/rainbow-mind-machine/boring-mind-machine
edit_uri: ""

pages:
  - 'Home':              'index.md'
  - 'Boring Keymaker':   'keymaker.md'
  - 'Boring Shepherd':   'shepherd.md'
  - 'Boring Sheep':      'sheep.md'
  - 'Boring Lumberjack': 'lumberjack.md'

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT License</a>. rainbowmindmachine@charlesreid1.com<br />Photo Credit: <a href="https://www.flickr.com/photos/russloar/">Russ Loar</a> under the <a href="https://creativecommons.org/licenses/by-nc-nd/2.0/">CC BY-NC-ND License</a><br /><br /><br />
  <div class="classictemplate template" style="display: block;">
    <div id="groupsio_embed_signup"> 
    <form action="https://groups.io/g/rainbowmindmachine/signup?u=3775286196230193988" method="post" id="groupsio-embedded-subscribe-form" name="groupsio-embedded-subscribe-form" target="_blank"> 
        <div id="groupsio_embed_signup_scroll"> 
          <label for="email" id="templateformtitle">
          <p style="font-size: 22px;">YOU WANT TO SUBSCRIBE TO THE <a href="https://groups.io/g/rainbowmindmachine">RAINBOW MIND MACHINE MAILING LIST</a></p>
          </label> 
          <input value="" name="email" class="email input-group input-group-lg" id="email" placeholder="email address" required="" type="email"> 
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input name="b_3775286196230193988" tabindex="-1" value="" type="text"></div> 
        <div id="templatearchives"></div> 
        <input value="Subscribe" name="subscribe" id="groupsio-embedded-subscribe" class="button btn btn-primary btn-lg dropdown-toggle" type="submit"> 
      </div>
    </form>
    </div>
    </div><br /><br />'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  logo:
    icon: 'settings_input_component'
  font:
    text: 'Roboto Slab'
    code: 'Ubuntu Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
